apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-nodepool
webhooks:
  - name: node.nodepool.io
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      url: "https://node.nodepool.io/mutating"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVZGJNQ29xbGNMSE5HQ0JxTFl0Lzcxc293YUVnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUI0WERUSXlNRFF4TWpBeU5ETTFNbG9YRFRJegpNRFF4TWpBeU5ETTFNbG93RnpFVk1CTUdBMVVFQXd3TVlXUnRhWE56YVc5dVgyTmhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0d0ZkYjNBdnpmOHF3R09GNzdnUlpBaFRZRXVGUFNIOURmUC8KSVNRODFJWS9wQU0vNXc4V2VDTTNrdU1MTHhGWFQ5SWdqUmkzeGZxTzZGcSsrNS8xNVVqSFRGU0hsY1c2OGxvNwpYV2tKOVdHdlFaMjVablNrTXJibXlFdnNBSXA1UDEyb0pkdHdLclQxSVBSczNEYW9USXNSN05kcEozNi9kMXYrCnlhS0N6VXNEV3pLZUswUDd2bTUzeitWSEh4eUhUeXdRb0xlQ3Ztakh2UkxFT0huaDFoRTExUEV1dEFHZHo1SGEKdXp3Qk1KK3NQamhpM3BqN3RpQ3dzMGs5bXpjQzFVTVU1emVoU01pMEVBdGp2YWRJUlg5Uk50QTVKcTdjRXkrcwo2bkNoaTQ4a09EWmk2R0FiRTM2aDNVOVJBVFVMRjM5TzlyeE45QWJMbysyNHJwQmFjd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVUJBNk9sdVVTazd3V09kRExkNEk1Tk5qdFQ4SXdId1lEVlIwakJCZ3dGb0FVQkE2T2x1VVMKazd3V09kRExkNEk1Tk5qdFQ4SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBZEZRNG1zWFFxYUp2QUliM3NXTGdCOUZWdC9YSjlHTjZTdytMRUk0QWkzUDJML1djVXYvVVM1ckZORUFSCi9IN0NpU2EySlZTZUw5Y0djb3JydG1CNFc1NVFPQ3l1M25OM0YwUXdVaFBhYStKSG5nY2NZdjVmQ2tIVVgwZHUKL0UyRGNjZm0zRVlEQWc1azV1RGFZalREQSthWnlSRDVPdHRQTUNweGxSeXQ2SXZwM3g3T1l3NTZ3clBaRStZNQpUS2ZLcGdvMCsyNE14QUpVWHJ3WEZZSzBUY2p4Qjl3YmlPK3k1NjBJL29GT21BQXhheXBpODdNdXRtdHBiWlovCklOcjB1NVYvNyttc05hRHRaZFJZeUJPTE5hYkg4bzNSR3ZKcFQ1czBSa2VaRDRCUE5xVlIvaWh3bnJyb1RzdVQKWERxK0VhdTRDeEY1eTBpRnQxc0hoeThteFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]